X-Account-Key: account5
X-UIDL: GmailId127fca96495a0df8
X-Mozilla-Status: 0000
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
Delivered-To: mlsubscriber.tech@csmining.org
Received: by 10.142.69.10 with SMTP id r10cs16488wfa;
        Wed, 14 Apr 2010 07:11:53 -0700 (PDT)
Received: by 10.103.4.4 with SMTP id g4mr4216317mui.80.1271254312418;
        Wed, 14 Apr 2010 07:11:52 -0700 (PDT)
Return-Path: <bounce-debian-user=mlsubscriber.tech=csmining.org@lists.debian.org>
Received: from liszt.debian.org (liszt.debian.org [82.195.75.100])
        by mx.google.com with ESMTP id 23si2270424mum.26.2010.04.14.07.11.51;
        Wed, 14 Apr 2010 07:11:52 -0700 (PDT)
Received-SPF: pass (google.com: manual fallback record for domain of bounce-debian-user=mlsubscriber.tech=csmining.org@lists.debian.org designates 82.195.75.100 as permitted sender) client-ip=82.195.75.100;
Authentication-Results: mx.google.com; spf=pass (google.com: manual fallback record for domain of bounce-debian-user=mlsubscriber.tech=csmining.org@lists.debian.org designates 82.195.75.100 as permitted sender) smtp.mail=bounce-debian-user=mlsubscriber.tech=csmining.org@lists.debian.org; dkim=neutral (body hash did not verify) header.i=@csmining.org
Received: from localhost (localhost [127.0.0.1])
	by liszt.debian.org (Postfix) with QMQP
	id 33B4A13A567A; Wed, 14 Apr 2010 14:11:40 +0000 (UTC)
Old-Return-Path: <celejar@csmining.org>
XChecker-Version: SpamAssassin 3.2.5 (2008-06-10) on liszt.debian.org
XLevel: 
XStatus: No, score=-8.0 required=4.0 tests=CAPINIT,LDOSUBSCRIBER,
	LDO_WHITELIST autolearn=failed version=3.2.5
X-Original-To: lists-debian-user@liszt.debian.org
Delivered-To: lists-debian-user@liszt.debian.org
Received: from localhost (localhost [127.0.0.1])
	by liszt.debian.org (Postfix) with ESMTP id B759B13A558C
	for <lists-debian-user@liszt.debian.org>; Wed, 14 Apr 2010 14:11:34 +0000 (UTC)
X-Virus-Scanned: at lists.debian.org with policy bank en-ht
X-AmavisStatus: No, score=-4 tagged_above=-10000 required=5.3
	tests=[BAYES_00=-2, CAPINIT=3, LDO_WHITELIST=-5] autolearn=no
Received: from liszt.debian.org ([127.0.0.1])
	by localhost (lists.debian.org [127.0.0.1]) (amavisd-new, port 2525)
	with ESMTP id EZNJrj5kvqo4 for <lists-debian-user@liszt.debian.org>;
	Wed, 14 Apr 2010 14:11:27 +0000 (UTC)
X-policyd-weight: using cached result; rate:hard: -6.9
Received: from mail-pz0-f171.google.com (mail-pz0-f171.google.com [209.85.222.171])
	by liszt.debian.org (Postfix) with ESMTP id A895313A555D
	for <debian-user@lists.debian.org>; Wed, 14 Apr 2010 14:11:26 +0000 (UTC)
Received: by pzk1 with SMTP id 1so120278pzk.18
        for <debian-user@lists.debian.org>; Wed, 14 Apr 2010 07:11:19 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=csmining.org; s=gamma;
        h=domainkey-signature:received:received:date:from:to:subject
         :message-id:in-reply-to:references:x-mailer:mime-version
         :content-type:content-transfer-encoding;
        bh=DfoTjvpQsdO4UXvmwpGL/LRJrihPKB3W244uI9FNRXM=;
        b=RPY49gGfaXF3HtlX92+jjFzW/6HTRUsDh/nLu/xnxqH5NrYrvIdDFTitvfmi3J/SZQ
         rC+r4l9SxcqhWUt+K5UawAAgd+PhhImXCaTpj7TGdh/7IfD5TDdrxkFDYiVDmlRX/A1a
         ppEDHbpYfTAp4bEJooBibZoS7JqAWt/oKPKTI=
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=csmining.org; s=gamma;
        h=date:from:to:subject:message-id:in-reply-to:references:x-mailer
         :mime-version:content-type:content-transfer-encoding;
        b=F7xjh1CHfTrezTATtVEhL64rbdgbh1n9ZfD5ZmZlbyzMkrJ7mG0HMd9zoLfrQou1Cu
         2Ii5YDTjXZNj9xtKDNg7ELoZVmGwiyyUe9t4fTNvpERDEdK9e1V8HtGPUu3m/JjJTY2e
         4LIO1qoQf0TGx6uw1Z/MR8nwwDLg05BWVDIZ0=
Received: by 10.140.247.18 with SMTP id u18mr1645942rvh.36.1271254278630;
        Wed, 14 Apr 2010 07:11:18 -0700 (PDT)
Received: from localhost.localdomain (pool-173-68-47-61.nycmny.east.verizon.net [173.68.47.61])
        by mx.google.com with ESMTPS id cm22sm117961ibb.17.2010.04.14.07.11.16
        (version=TLSv1/SSLv3 cipher=RC4-MD5);
        Wed, 14 Apr 2010 07:11:17 -0700 (PDT)
Date: Wed, 14 Apr 2010 10:11:14 -0400
From: Celejar <celejar@csmining.org>
To: debian-user@lists.debian.org
Subject: Re: Reportbug-ng Cannot Retrieve Info
Message-Id: <20100414101114.7d7993ec.celejar@csmining.org>
In-Reply-To: <201004141637.57106.d_baron@012.net.il>
References: <201004141637.57106.d_baron@012.net.il>
X-Mailer: Sylpheed 3.0.1 (GTK+ 2.20.0; i486-pc-linux-gnu)
Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
X-Rc-Virus: 2007-09-13_01
X-Rc-Spam: 2008-11-04_01
Resent-Message-ID: <9j7AZM43BkI.A.4JD.c0cxLB@liszt>
Resent-From: debian-user@lists.debian.org
X-Mailing-List: <debian-user@lists.debian.org> archive/latest/574041
X-Loop: debian-user@lists.debian.org
List-Id: <debian-user.lists.debian.org>
List-Post: <mailto:debian-user@lists.debian.org>
List-Help: <mailto:debian-user-request@lists.debian.org?subject=help>
List-Subscribe: <mailto:debian-user-request@lists.debian.org?subject=subscribe>
List-Unsubscribe: <mailto:debian-user-request@lists.debian.org?subject=unsubscribe>
Precedence: list
Resent-Sender: debian-user-request@lists.debian.org
Resent-Date: Wed, 14 Apr 2010 14:11:40 +0000 (UTC)

On Wed, 14 Apr 2010 16:37:55 +0300
David Baron <d_baron@012.net.il> wrote:

> On my Debian Sid box, get:
> Traceback (most recent call last):
>   File "/usr/share/reportbug-ng/rnggui.py", line 205, in 
> lineedit_return_pressed
>     buglist = bts.get_bugs(query)
>   File "/usr/lib/pymodules/python2.5/debianbts.py", line 184, in get_bugs
>     reply = server.get_bugs(*key_value)
>   File "/usr/lib/pymodules/python2.5/SOAPpy/Client.py", line 470, in __call__
>     return self.__r_call(*args, **kw)
>   File "/usr/lib/pymodules/python2.5/SOAPpy/Client.py", line 492, in __r_call
>     self.__hd, self.__ma)
>   File "/usr/lib/pymodules/python2.5/SOAPpy/Client.py", line 363, in __call
>     config = self.config)
>   File "/usr/lib/pymodules/python2.5/SOAPpy/Client.py", line 187, in call
>     r.endheaders()
>   File "/usr/lib/python2.5/httplib.py", line 860, in endheaders
>     self._send_output()
>   File "/usr/lib/python2.5/httplib.py", line 732, in _send_output
>     self.send(msg)
>   File "/usr/lib/python2.5/httplib.py", line 699, in send
>     self.connect()
>   File "/usr/lib/python2.5/httplib.py", line 683, in connect
>     raise socket.error, msg
> socket.error: (111, 'Connection refused')
> 
> and cannot retrieve any information with this program. Problem began yesterday 
> but I know of know upgrades effecting this.

What do you get with regular reportbug?  It looks like there may be
some sort of connection problem on your system.  In any event, I'd file
a bug, since the program really ought to inform the user of the problem
and terminate gracefully, rather than dump an ugly Python trackback.

Celejar
-- 
foffl.sourceforge.net - Feeds OFFLine, an offline RSS/Atom aggregator
mailmin.sourceforge.net - remote access via secure (OpenPGP) email
ssuds.sourceforge.net - A Simple Sudoku Solver and Generator


-- 
To UNSUBSCRIBE, email to debian-user-REQUEST@lists.debian.org 
with a subject of "unsubscribe". Trouble? Contact listmaster@lists.debian.org
Archive: http://lists.debian.org/20100414101114.7d7993ec.celejar@csmining.org


